[package]
name = "cmtk"
version = "0.2.1"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
logos = "0.16.1"
rowan = "0.16.1"
serde = { version = "1.0.228", features = ["derive"] }
similar = "2"
toml = "1.1.2"

[dev-dependencies]
assert_cmd = "2.0.18"
proptest = "1.11.0"
tempfile = "3.17.1"
walkdir = "2.5.0"
